[[./情報応用2013日文_02.org][情報応用2013日文/02]]

** アウトラインプロセッサーの演習

*** 

以下の内容を何回か適当な回数の講義で行いましょう。

最終的に，アウトラインプロセッサの使い方を覚え，文書の構造を捕まえつつ，アウトラインプロセッサでレポートを作成したり，

以下の課題について，[[./st_学生番号_アウトラインプロセッサ.org][st/学生番号/アウトラインプロセッサ]]
というページを作成し，まとめてください。

*** [課題] アウトラインプロセッサーとは？

どんなものか調べてWikiにまとめましょう。

-  最初は簡単なまとめを作り，回を重ねてよりよいものにしてください。

*** [課題] BEITEL概要のまとめ

BEITELの[[http://beitel.carabiner.jp/][説明]]を読んで理解し，Wikiにまとめましょう。

-  知らない言葉や概念があれば，列挙し，調べ理解し，簡単なメモを作ってください。

*** 文書の書き方

BEITELの[[http://beitel.carabiner.jp/tutorial.html][文書の書き方]]
をひと通り読んで試してみる

*** 「アウトラインプロセッサで書け!」のまとめをBEITELで作成してみる

[[http://pctraining.s21.xrea.com/knowledge_tools/outline-proccessor.html][アウトラインプロセッサで書け]]
を読み，BEITELにコピペして，自分なりのまとめを作ってみる

*** 自分なりの使い方を考えてみる

どんなことに使えそうか，自分なりに考えてみる。

他の人はどう考えているか，他の人の考えを見たり，インターネット検索して，調べまとめよう。

*** Writer/Word のアウトライン機能を使ってみる

** 検討中の課題

*** BEITELを使って他の形式の文書を作る，変換する

下記の形式の文書へ変換することができます。

-  テキスト
-  HTML
-  OPML
-  PDF
-  Word

*** BEITLE のアプリケーションを作ってみる

BEITELの機能を拡張するためのアプリ（他人が作ったプログラム）があります．
BEITELに組み込むことができます。

-  BEITLE のアプリケーションとインストール

-  オリジナル・アプリケーションの作成

-  アプリケーションから呼び出し可能なAPI

**** Wiki <-> BEITEL

Wiki形式の文書がつくれるようなアプリケーションを作成したいと思っています。
- (2013.9.30, [[s-:]])
