[[./情報処理_タイピング.org][情報処理/タイピング]]

*** タイピング練習ソフトウェア

[[http://typing.sakura.ne.jp/sushida/][寿司打]] を使いましょう。

*** タイピングの練習


- 難易度は，「普通」を選ぶ
- コースは，お手軽3000円




  

-  タッチタイピング（キーボードを見ずにキー入力する）ができるようになりましょう。

-  まずキーボードの各文字の場所を覚えましょう。[[http://www.wawawa.co.jp/keyboard/guidance/2.htm][参考サイト]]

*** 記録

タイピングの結果を記録しましょう。

アプリは，「メモ帳」を使いましょう。

日付，回目, 入力文字数，平均キータイプ数，ミスタイプ数,
獲得金額，順位を記録します。

*CSV形式*を使って*表の形式*で記録します。 -
CSV形式とはデータを半角コンマで区切って並べたものです。 -
先頭に半角コンマを書き, 続いて，日付，回目,
入力文字数，平均キータイプ数，ミスタイプ数,
獲得金額，順位を半角コンマで区切って並べます。

下記のように記入します。

#+BEGIN_EXAMPLE
    ,日付，回目, 入力文字数，平均キータイプ数，ミスタイプ数, 獲得金額，順位
#+END_EXAMPLE

例えば，下記のような記録になります。省略した箇所は，空白にして，コンマは省かず記入します。

#+BEGIN_EXAMPLE
    ,日付, 回, 入力文字数, 平均キータイプ数, ミスタイプ数
    ,2014.1.14, 1, 167, 2.5, 10, 2850, 4223
    ,         , 2, 153, 2.4, 8, 2700, 4347
    ,         , 3, 163, 2.4, 7, 2700, 4300
    ,         , 4, 153, 2.4, 8, 2850, 4355
    ,         , 5, 153, 2.4, 8, 2700, 4380
    ,2014.1.21, 1, 173, 2.6, 11, 3000, 4000
    ,         , 2, 169, 2.5, 12, 3000, 4000
    ,         , 3, 171, 2.6, 10, 3000, 4000
    ,         , 4, 171, 2.6, 10, 3000, 4000
    ,         , 5, 171, 2.6, 10, 3000, 4000
#+END_EXAMPLE

毎回一番末尾に結果を追加記録し，保存します。

**** タイピング記録のコピー（バックアップを作る)

毎回，タイピング記録のコピー.csv という名前でコピーを作りましょう。
何かのはずみに記録をなくした時に，役立ちます。

バックアップは，USBメモリやDropbox
にも作ると更にデータの喪失に備えられます。

**** CSVファイルをメモ帳で開く

-  タイピング.csv を右クリックし
-  プログラムから開くを選び，
-  テキストエディタが表示されていればそれをダブルクリックします。
-  表示されていなければ，参照を選び，

   -  動かしたいプログラムを選びます

-  OK をクリックするとテキストエディタが開きます。

**** Wikiへの保存と表示

-  タイピング記録.csv をメモ帳で開き，
-  すべての行を選び，コピーします。

   -  見えませんが，クリップボードというところにコピーされます。

-  Wikiのタイピング記録ページを開きます。
-  編集ボタンを押して，編集モードに入ります。
-  ページの末尾に，（コピーしたタイピング記録のCSV
   データを）貼り付けます。
-  保存すると，表形式で表示される。

例えば，先ほどの CSV は，

,日付, 回, 入力文字数, 平均キータイプ数, ミスタイプ数 ,2014.1.14, 1,
167, 2.5, 10, 2850, 4223 , , 2, 153, 2.4, 8, 2700, 4347 , , 3, 163, 2.4,
7, 2700, 4300 , , 4, 153, 2.4, 8, 2850, 4355 , , 5, 153, 2.4, 8, 2700,
4380 ,2014.1.21, 1, 173, 2.6, 11, 3000, 4000 , , 2, 169, 2.5, 12, 3000,
4000 , , 3, 171, 2.6, 10, 3000, 4000 , , 4, 171, 2.6, 10, 3000, 4000 , ,
5, 171, 2.6, 10, 3000, 4000
