* タイピング練習と記録メモ

このページは書きかけです。- <2016.04.12, masayuki>

** 練習用 Web アプリ

[[http://typing.sakura.ne.jp/sushida/][寿司打]] を使いましょう。

** 練習の難易度

後で練習成果を可視化するので，同じ練習難度でやりましょう。

- 難易度は，「普通」を選ぶ
- コースは，お手軽3000円

-  できれば，タッチタイピング（キーボードを見ずにキー入力する）ができるようになりましょう。

-  まずキーボードの各文字の場所を覚えましょう。[[http://www.wawawa.co.jp/keyboard/guidance/2.htm][参考サイト]]

** 結果のメモ

- タイピングの結果をめもしましょう。

- 記録するための Windows アプリは，「メモ帳」を使いましょう。
  後で，エクセルで表やグラフにします。

- ファイル名は，「タイピングメモ」にして，自分の「情報処理演習フォルダ」の中に保存します。

- 日付，回目, 入力文字数，平均キータイプ数，ミスタイプ数を半角コンマで区切って並べます。

  - 数字やコンマは *半角英数字* にします。

  - 獲得金額や順位も保存したければ，やはり半角コンマで区切って，行の後ろに続けて書きます。
  - データを半角コンマで区切って並べたものを *CSV* 形式と呼びます。
  - CSV形式のデータは，エクセルに *表* として，取り込めます。
  
- 獲得金額や順位も保存したければ，やはり半角コンマで区切って，行の後ろに続けて書きます。

下記のように記入します。

#+BEGIN_EXAMPLE
  日付, 回目, 入力文字数, 平均キータイプ数, ミスタイプ数
#+END_EXAMPLE

例えば，下記のような記録になります。省略した箇所は，空白にして，コンマは省かず記入します。

#+BEGIN_EXAMPLE
    日付, 回, 入力文字数, 平均キータイプ数, ミスタイプ数
    2014.1.14, 1, 167, 2.5, 10
             , 2, 153, 2.4, 8
             , 3, 163, 2.4, 7
             , 4, 153, 2.4, 8
             , 5, 153, 2.4, 8
    2014.1.21, 1, 173, 2.6, 11
             , 2, 169, 2.5, 12
             , 3, 171, 2.6, 10
             , 4, 171, 2.6, 10
             , 5, 171, 2.6, 10
#+END_EXAMPLE

毎回一番末尾に結果を追加記録し，保存します。

**** タイピングメモのコピー（バックアップを作る)

毎回，タイピングメモのコピー という名前でコピーを作りましょう。
何かのはずみに記録をなくした時に，役立ちます。

バックアップは，USBメモリや GoogleDrive
にも作ると更にデータの喪失に備えられます。


* 以下更新が必要です。- <2016.04.12, masayuki>

**** CSVファイルをメモ帳で開く

-  タイピング.csv を右クリックし
-  プログラムから開くを選び，
-  テキストエディタが表示されていればそれをダブルクリックします。
-  表示されていなければ，参照を選び，

   -  動かしたいプログラムを選びます

-  OK をクリックするとテキストエディタが開きます。

**** Wikiへの保存と表示

-  タイピング記録.csv をメモ帳で開き，
-  すべての行を選び，コピーします。

   -  見えませんが，クリップボードというところにコピーされます。

-  Wikiのタイピング記録ページを開きます。
-  編集ボタンを押して，編集モードに入ります。
-  ページの末尾に，（コピーしたタイピング記録のCSV
   データを）貼り付けます。
-  保存すると，表形式で表示される。

例えば，先ほどの CSV は，

,日付, 回, 入力文字数, 平均キータイプ数, ミスタイプ数 ,2014.1.14, 1,
167, 2.5, 10, 2850, 4223 , , 2, 153, 2.4, 8, 2700, 4347 , , 3, 163, 2.4,
7, 2700, 4300 , , 4, 153, 2.4, 8, 2850, 4355 , , 5, 153, 2.4, 8, 2700,
4380 ,2014.1.21, 1, 173, 2.6, 11, 3000, 4000 , , 2, 169, 2.5, 12, 3000,
4000 , , 3, 171, 2.6, 10, 3000, 4000 , , 4, 171, 2.6, 10, 3000, 4000 , ,
5, 171, 2.6, 10, 3000, 4000
