* 利用するIDとパスワード

** ID とパスワード

*ID* はあなたの *識別名* で，その *パスワード* は自分だけが知っている
*秘密の言葉* です。

IDとパスワードの組み合わせが，利用する *システム* に *登録* されていています。

*ログイン* とは，システムにIDとパスワードの組を入力することで，
自分であることを認証してい，システム内部に入って，内部の情報を使える状態になることです。

IDは一度決まると普通変更できませんが，パスワードは変更可能です。

*** 盛岡大学で使うシステム

ここでいう *システム* とは，コンピュータやインターネットサイトで，

1. 本人確認の認証を受けてシステム内部に入ると，

2. 自分の情報やサービスを扱える

ようなものをいいます。

盛岡大学で使うコンピュータやネットワークサービスで，IDとパスワードが必
要なシステムには，以下のものがあります:

-  端末室のPC

-  Webメール

-  学務用の盛岡大学ポータルサイト

**** 盛岡大学ポータルサイト

学年暦や学務からのお知らせ，出席簿，シラバスがあります。

-  端末とは別のIDでログインします。

-  大学からの配布資料を確認してください

**** Webメール

盛岡大学が運用しているメールサーバを

-  Webメールで，ブラウザからログインします。
-  端末と同じIDとパスワードでログインします。

使い方は別に紹介します。

**** 端末室のPC

A306, A311, B313, 図書館にある端末室のPC達です。

ID (識別名)とパスワードが配布されています。

端末室のPCを使うために使います。

***** パスワードの変更

配布されたIDを変更することはできませんが，パスワードは自分と管理者だけが変更できます。

配布されたパスワードは，機械的に作られていて，覚えにくく忘れやすいものです。

「Control」キー，「Alt」キー，「Delete]キー を同時押しすると，
いくつかのメニュー項目が現れ， その中にパスワード変更メニューがある。

**** IDやパスワードを忘れたら

学務係の人にその旨，伝えてください。

** パスワードについて

自分には覚えやすく，他人からは覚えにくく，類推しにくい文字の列にしましょう。

下記ページやサイトを参考にしてください：

-  [[./情報処理_パスワードのよしあし.org][パスワードについて]]

-  [[http://www.lifehacker.jp/2011/05/110512easy-password-guess.html][パスワード破りのプロはこうやってアナタのパスワードを見破っている]]

-  [[http://www.lifehacker.jp/2010/04/100401passwordcrack.html][どうやってはっきんぐされるか？]]


