https://honto.jp/cp/hybrid/writers-interview/004-fujiharakazuhiro.html

* 人生を変える勉強をしよう

** 原文

みなさんは気づいているでしょうか。日本では１９９７年に、はっきりと時代
の変わり目がやってきました。

97年以前の日本は、20世紀型の成長社会。キーワードを挙げるなら「みんな一
緒」。何事にも、あらかじめ用意された正しい解答があると考えられていて、
その正解へ真っ先に行き着くことがよしとされました。

仕事の現場では、物事を早くきちんと、真面目な態度でこなす能力が求められ
ました。生活面では、あらかじめ提示されたものを消費するのが奨励されます。
建売住宅を購入し、勧められるがまま保険に入り、流行のレジャーにいっせい
に飛びつくといったことです。子どもの学習も、情報を早くきちんと処理する
手段を身に付けることが目的でした。

ところが、98年以降はあきらかに時代が変わります。成熟社会を迎え、価値観
が「それぞれ一人ひとり」へとシフトしました。もう決まった正解はどこにも
ありません。あるのはただ、自分自身の頭で考え導き出した、それぞれの納得
解だけ。

仕事でも生活でも、単に入ってきたものを右から左へ受け流すのではなく、情
報をみずから編集する力が求められます。学びのかたちも、ただ知識を詰め込
むだけでは意味がありません。これからは頭の柔らかさや、いろんな角度から
物事を見る複眼的な思考、知識を応用して実地に活かす能力などが求められ、
それらを得るためのトレーニングが必要となってきたのです。

いまやすっかり、インターネット全盛の社会ですよね。そんな時代に人は、否
応なく大きく２つのタイプに分かれてしまいます。情報を生み出す側の人と、
情報をひたすら消費する側の人です。

情報を消費するだけでも時間はいくらでもつぶせますが、それだけではいつか、
むなしく感じるときがやってくるのでは？　自分の存在感を増していったり、
生きていることを実感するには、情報を生み出す側に回らないといけません。
そのためにはどうするか。自分にしかできないことを見つけ、それを他の人に
もわかるようなかたちにして、だれかに届けるためうまく発信していく必要が
ある。そういうことができるような学びを、積み上げていかなければいけませ
んね。

ここでいう勉強とは、国語・算数・理科・社会・英語といった教科ではありま
せん。それらは、20世紀に有効だった学習の型。情報編集力が求められる21世
紀成熟社会には、通用しづらくなっています。

新しい情報活用能力、すなわちリテラシーがいまこそ求められているのです。
どんなものかといえば、\\
・シミュレーション能力\\
・コミュニケーション能力\\
・ロジカルシンキング能力\\
・ロールプレイング能力\\
・プレゼンテーション能力\\
この５つのリテラシーです。

いまは正解がない時代なのだから、何かをするときは常に、自分で仮説を立て
ていかなければいけません。仮説を構築する力が、シミュレーション能力です。
よりよい解を求めるには、多くの人の知恵を持ち寄ったほうがいい。そのアレ
ンジをするための力が、コミュニケーション能力です。

情報が氾濫する時代だからこそ、物事を疑い検証する態度も重要です。正しく
疑う力、それがロジカルシンキング能力。別の角度から状況を眺める冷静さも
大事ですね。そうした目を保てるのが、ロールプレイング能力。自分の能力を
最大限にアピールするためのプレゼンテーション能力も含めて、これらがいま
と今後の社会を生きていくために、必須の力となっているのです。

これから学校で勉強をする人たちは、そのあたりを意識して学びに向かうべき。
では、すでに20世紀型の学習を経てきた大人はどうすればいいか。まずは、自
覚することです。自分が情報処理力重視の「正解主義」学習をしてきたことに。
そうして改めて、情報編集力を磨くための「修正主義」学習を、折に触れ心が
けていきましょう。常に頭を柔らかくしておく、それがポイントになってきま
すよ。

人はなぜ学ぶのか。幸せに生きるためですね。20世紀までは、幸せのかたちと
いうものがたしかにありました。いい成績をとっていい会社に入り、子をもう
けて孫の顔を見て......。でも、そんな定型は崩れました。会社も国も、何も
保証してくれません。

一人ひとりが、それぞれの幸福論を編集しないと、幸せを見つけられなくなっ
ているのです。自由度は格段に上がったけれど、自由ってじつは、使いこなす
のがたいへんなもの。自分の頭でしっかり考えないと、自由を持て余し、幸せ
は遠ざかってしまう。

幸福を得るための手段として、自身の情報編集力を磨かないといけない。その
営みこそが、いまの時代の本当の「学び」なのですよ。


* 章分け

** ~1997 皆一緒の時代
みなさんは気づいているでしょうか。日本では１９９７年に、はっきりと時代
の変わり目がやってきました。

97年以前の日本は、20世紀型の成長社会。キーワードを挙げるなら「みんな一
緒」。何事にも、あらかじめ用意された正しい解答があると考えられていて、
その正解へ真っ先に行き着くことがよしとされました。

仕事の現場では、物事を早くきちんと、真面目な態度でこなす能力が求められ
ました。生活面では、あらかじめ提示されたものを消費するのが奨励されます。
建売住宅を購入し、勧められるがまま保険に入り、流行のレジャーにいっせい
に飛びつくといったことです。子どもの学習も、情報を早くきちんと処理する
手段を身に付けることが目的でした。

** 1998~ それぞれ一人ひとりの時代へ

ところが、98年以降はあきらかに時代が変わります。成熟社会を迎え、価値観
が「それぞれ一人ひとり」へとシフトしました。もう決まった正解はどこにも
ありません。あるのはただ、自分自身の頭で考え導き出した、それぞれの納得
解だけ。

仕事でも生活でも、単に入ってきたものを右から左へ受け流すのではなく、情
報をみずから編集する力が求められます。学びのかたちも、ただ知識を詰め込
むだけでは意味がありません。これからは頭の柔らかさや、いろんな角度から
物事を見る複眼的な思考、知識を応用して実地に活かす能力などが求められ、
それらを得るためのトレーニングが必要となってきたのです。

** インターネット全盛の社会時代

いまやすっかり、インターネット全盛の社会ですよね。そんな時代に人は、否
応なく大きく２つのタイプに分かれてしまいます。情報を生み出す側の人と、
情報をひたすら消費する側の人です。

** 情報を生み出す

情報を消費するだけでも時間はいくらでもつぶせますが、それだけではいつか、
むなしく感じるときがやってくるのでは？　自分の存在感を増していったり、
生きていることを実感するには、情報を生み出す側に回らないといけません。
そのためにはどうするか。自分にしかできないことを見つけ、それを他の人に
もわかるようなかたちにして、だれかに届けるためうまく発信していく必要が
ある。そういうことができるような学びを、積み上げていかなければいけませ
んね。

ここでいう勉強とは、国語・算数・理科・社会・英語といった教科ではありま
せん。それらは、20世紀に有効だった学習の型。情報編集力が求められる21世
紀成熟社会には、通用しづらくなっています。

** 情報リテラシー

新しい情報活用能力、すなわちリテラシーがいまこそ求められているのです。

この５つのリテラシーです:

- シミュレーション能力 ::

     いまは正解がない時代なのだから、何かをするときは常に、自分で仮説
     を立てていかなければいけません。仮説を構築する力が、シミュレーショ
     ン能力です。

- コミュニケーション能力 ::

     よりよい解を求めるには、多くの人の知恵を持ち寄ったほうがいい。そ
     のアレンジをするための力が、コミュニケーション能力です。

- ロジカルシンキング能力 ::

     情報が氾濫する時代だからこそ、物事を疑い検証する態度も重要です。
     正しく疑う力、それがロジカルシンキング能力。

- ロールプレイング能力 ::

     別の角度から状況を眺める冷静さも大事ですね。そうした目を保てるの
     が、ロールプレイング能力。

*** プレゼンテーション能力

    自分の能力を最大限にアピールするためのプレゼンテーション能力


これらがいまと今後の社会を生きていくために、必須の力となっているのです。

これから学校で勉強をする人たちは、そのあたりを意識して学びに向かうべき。


** 「正解主義」学習から「修正主義」学習に

では、すでに20世紀型の学習を経てきた大人はどうすればいいか。

1. まずは、自覚することです。自分が情報処理力重視の「正解主義」学習を
   してきたことに。

2. そうして改めて、情報編集力を磨くための「修正主義」学習を、折に触れ
   心がけていきましょう。常に頭を柔らかくしておく、それがポイントになっ
   てきますよ。

** 幸せに生きるための学び

   人はなぜ学ぶのか。幸せに生きるためですね。

*** 20世紀まではの幸せのかたち

    20世紀までは、幸せのかたちというものがたしかにありました。いい成績
    をとっていい会社に入り、子をもうけて孫の顔を見て......。

*** 21世紀の幸せのかたち

    でも、そんな定型は崩れました。会社も国も、何も保証してくれません。

    一人ひとりが、それぞれの幸福論を編集しないと、幸せを見つけられなく
    なっているのです。自由度は格段に上がったけれど、自由ってじつは、使
    いこなすのがたいへんなもの。自分の頭でしっかり考えないと、自由を持
    て余し、幸せは遠ざかってしまう。

*** 幸福を得るために自身の情報編集力を磨く

    幸福を得るための手段として、自身の情報編集力を磨かないといけない。
    その営みこそが、いまの時代の本当の「学び」なのですよ。
