* 2019.04.08 1回目

** はじめに
入学おめでとうございます。

楽しくやっていきましょう。

このページには，今日の講義の内容と進行の予定を書いています。

インターネット・エクスプローラを使って見てください。

このページの中には，他のページを指している箇所 ( * リンク * )が，たくさんで
てきます。リンクを示す文字列は，青く色がついています。

そのリンクをクリックすると新らしいページが開きます。同時に
複数ページを開いていることが多いので，迷いやすいので注意してください。

リンクを開く時は，右クリックで開いてみて下さい。新らしいタブで開くの
で，同時に開いているページがわかりやすくなります。


** [[https://ja.wikipedia.org/wiki/情報リテラシー][情報リテラシー - Wikipedia]]

この講義の大きな目的は，情報の処理ができるようになることです。

#+BEGIN_QUOTE

情報リテラシー（じょうほうリテラシー、information literacy）とは、情報
(information)と識字 (literacy) を合わせた言葉で、情報を自己の目的に適
合するように使用できる能力のことである。「 情報活用能力」や「情報活用
力」、「情報を使いこなす力」とも表現する。

[[https://ja.wikipedia.org/wiki/情報リテラシー][情報リテラシー - Wikipedia]]

#+END_QUOTE


** ガイダンス

今日は，下記のページにしたがって，講義の説明をします:

- {{{ll(guidance,ガイダンス)}}}

先生の自己紹介をします:
- {{{lll(s,先生,自己紹介,sec-1)}}}
  
** 今日の課題

以下，今日やることです。

*** IDとパスワードの設定

{{{lll(pc,パソコンの使い方,IDとパスワード,sec-1)}}} を読んでください。

-  良いパスワードを考えてきた人は, パスワードを設定しましょう。
-  良くないパスワードだったり，パスワードを考えて来なかった人は,
   良いパスワードを考えましょう。

*** コンピュータ環境の確認と設定

パソコンで，自分の情報を保存し利用するための決まりごとです。

- {{{lll(pc,パソコンの使い方,ファイルやフォルダの決まりごと,sec-4)}}} 
- {{{lll(pc,パソコンの使い方,自分の情報の保存,sec-5)}}} 
- {{{lll(pc,パソコンの使い方,自分が管理する情報置場,sec-6)}}} 

何回も説明しますので，徐々に覚えてください。

忘れたら，何回でも質問してください。

*** Google 登録

{{{ll(google,Googleを利用しよう)}}} を読んで，[[http://google.com][Google]] に登録しましょう。

*** アンケートへの回答

皆さんの今の状況を知って講義の内容や説明のやり方の参考にしますので，
下記のリンクからアンケートを開き，回答し，送信してください。

- [[https://forms.gle/tdxn6mBcLbFmKBv48][A組へのアンケート]]
- [[https://forms.gle/F74YRCKrE8RtvNSY7][B組へのアンケート]]

*** 出席票の提出

下記のリンクから，記名し，回答し，送信してください。

- [[https://forms.gle/T2tUQgdFkPseKSug9][A組の出席票]]
- [[https://forms.gle/qF3tonD3d2quDBiZ8][B組の出席票]]


*** 紙の出席カードの提出

出席カード （紙）を配りますので，学生番号と氏名を書き，下記の内容について記述
して，提出してください。

- 自己紹介を書いてください
  
  - 出身地・出身高校 (あれば学科)
  - 趣味，得意，好きなこと、嫌いなことなどなど
  - 高校の情報でやったこと
  - 講義への要望など
  
** USBメモリ

   今年度はUSBメモリを使います。*来週まで*に用意してきてください．

   USBの中にアプリを入れて，使いますので，

   - アクセスが速くて, 
   - ある程度容量がある,

   ことが大切です。

   USB3.0 4G以上空きがあるモノを用意してください。

   持っていない人は，盛大生協においてある プリンストン PSUSB3-8G 710円
   がおすすめです。

   [[http://uzurea.net/usb-20-30-basic-knowledge/][今さら聞けない! USBの基礎知識『USB2.0と3.0の違いと見わけ方』]] を参考
   にしてください．

  
** 退室時の注意
- パソコンの電源を切るか，次に使う人がいる時はログオフしてください。
- 出席カードは，先生に手渡ししてください。


