** 不正ソフトの種類 ([[https://ja.wikipedia.org/wiki/%E3%83%9E%E3%83%AB%E3%82%A6%E3%82%A7%E3%82%A2)][マルウェア - Wikipedia]]より)

代表例をあげる。以下の種類は排他的ではなく、複数の種類の定義を満たすマ
ルウェアも存在しえる。

*** 狭義のコンピュータウイルス

あるいは単に狭義のウイルスとは他のプログラムやファイルの一部を書き換え
（寄生、感染）、自己複製する機能を持つマルウェアのことである。感染対象
のプログラムの事をウイルスの宿主もしくはホストプログラムという。

狭義のウイルスは感染経路を秘匿するなどの目的で、プログラムなどに感染し
たあと一時的に潜伏し、その後しばらく経ってから活動を開始（発病）するも
のも多い。

*** 広義のウイルス

文脈によって定義が様々であるが、 「コンピュータウイルス対策基準」では、
自己伝染機能、潜伏機能、発病機能のいずれかをもつ加害プログラムの事をウ
イルスの定義として採用している。

後述するワームやトロイの木馬は狭義のウイルスではないが、この意味での広
義のウイルスには属する。

最広義では「ウイルス」という語はマルウェアと同義であり、マスメディアな
どではこの最広義の意味に用いられるが、これは誤用であるとされることもあ
る。

*** ワーム

ウイルス同様自己増殖するが、ホストプログラムを持たず、単体で存在するマ
ルウェアの事を指す。

*** バックドア

外部からコンピューターを操るために作られたコンピューターへの不正な侵入
経路の事でRAT(Remote Administration Tool)とも呼ばれる。

バックドアをしかけるマルウェアをバックドア型と呼ぶ。

*** トロイの木馬

一見無害なファイルやプログラムに偽装した上でコンピューターに侵入したあ
と悪意のある振る舞いをするものを指すことが多いが、偽装を行わ
ずにOS等の脆弱性を悪用して勝手にインストールされてしまうもの(ドライブ
バイダウンロード)もトロイの木馬に含める場合がある。

狭義のウイルスと違い自己増殖機能は持たない。

トロイの木馬の定義として、コンピューター内部に侵入したあと攻撃者による
外部からの命令で悪意のある振る舞いをする[8][9][16]事やバックドア型であ
る事[16]を要件にする場合もある。

*** スパイウェア

情報収集を主な目的とし、コンピューターの内部情報を外部に勝手に送信する
ソフトウェアで、ユーザーが気づかないうちにパソコンにインストールしてい
るパターンが多い。

IPAとJNSAの定義によればスパイウェアとは「利用者や管理者の意図に反して
インストールされ、利用者の個人情報やアクセス履歴などの情報を収集するプ
ログラム等」のことである。

*** キーロガー

もしくはキーストロークロガーはキーボードからの入力を記録するソフトウェ
アのこと。コンピューターの所有者自身がデバッグのためにしかけるなどの使
い方もあるが、パスワードや個人情報などを奪取するため悪意を持ってしかけ
られるなどマルウェア（スパイウェア）として用いられることもある。同様に
ネットワークを通るパケットを監視するスニッファも盗聴目的で使われる場合
がある。

*** ボット

IRCなどを利用して攻撃者から命令を受け取り、命令に応じてDDoS攻撃やスパ
ムメール送信などを行うマルウェア。

*** ルートキット

攻撃者が被害者のコンピューターに侵入したあとに用いるツールを集めたパッ
ケージ[28]で、マルウェアとして被害者のコンピューターにしかける[29]。侵
入の発覚を防ぐログ改ざんツール[28]、バックドアをしかけるツール[28]、キー
ロガー[28]、パスワードやクレジットカード情報等の窃盗ツール[29]、DDoS攻
撃用のボット化ツール[29]、セキュリティソフトの無効化ツール[29]などが含
まれていることがある。こうした攻撃を容易にするため、システムバイナリを
含めたファイルを数百個単位で改ざんする[9]。ルート権限を奪うなど管理者
レベルのアクセス権を取得する事を定義とする場合もある[30]。

*** ランサムウェア(ransomware)

コンピューターをロックしたり重要なファイルを暗号化して読めなくするなど
して被害者を困らせ，身代金(ransom)を払えば元に戻すと脅迫するマルウェ
ア[31]。

*** スケアウェア(scareware)

とはユーザの恐怖(scare)心を煽る偽の警告メッセージ（「PCから違法ポルノ
やウイルスが検出された」等）を表示し、問題を解決するには所定の金額を支
払うようにと脅すマルウェア。

*** ダウンローダー

サイズの小さなマルウェアで、攻撃者のサーバから被害者のコンピューターに
実行ファイルなどをダウンロードするなどさらなる攻撃の足がかりにする。

*** アドウェア（Adware）

ユーザの望まない広告を勝手に出すソフトウェアである。アドウェアないしそ
の中の悪質なものもマルウェアの範疇に含める場合がある)。

