[[./st_1381112_最終レポート.org][st/1381112/最終レポート]]

*** ４章　　統計分析することの意味とは？

#+BEGIN_EXAMPLE
       ・情報をわかりやすく効率的にまとめることができる

       ・知りたいことや仮説を検証できる
#+END_EXAMPLE

*** ５章　　データの尺度

#+BEGIN_EXAMPLE
       ・名義尺度
         単に区別するために用いられている尺度。
         例えば、血液型でＡ型・Ｂ型・Ｏ型・ＡＢ型を、 それぞれ０・１・２・３と数値    に対応させたもの。


       ・順序尺度
         大小関係にのみ意味がある尺度。
         例えば、治療効果の判定において、 悪化・不変・改善・著効を、それぞれ-１・０・１・２と数値に対応させたもの。
         平均値は定義できないが中央値は定義できます。

       ・間隔尺度
         数値の差のみに意味がある尺度。
        「距離尺度」とも呼びます。順序尺度の性質も備えています。
         例えば、温度が10℃から15℃になったときに、50％の温度上昇があったとはいいま    せん。 温度が10℃から15℃になったときも、100℃から105℃になったときも、 と    もに５℃の温度上昇です。そして、５℃という数値には意味があります。

       ・比例尺度
         数値の差とともに数値の比にも意味がある尺度。
        「比尺度」とも呼びます。順序尺度・間隔尺度の性質も備えています。
         例えば、体重は50kgから60kgになったときと、100kgから110kgになったときと    は、 同じ10kgの増加であっても、前者は20％増、後者は10％増です。 また、比が定義できるということは絶対零点を持つことと同じことを表します。
#+END_EXAMPLE

*** 6章--データの処理と統計分析の流れ

分析の流れ

#+BEGIN_EXAMPLE
      1) 尺度の確定

      2) 記述統計 平均値とか、わかりやすく表現する

      3) 変数の変換 

      4) 推測統計
#+END_EXAMPLE

*** 7章--集計の意味

#+BEGIN_EXAMPLE
      7 集計の意味

      羅列されている生データを、
      視覚的に、あるいは数値で、
      簡単に表現
#+END_EXAMPLE

*** 8章--度数分布を描く

***** 度数分布とは

　　
それぞれの変数で、ある値もしくは値の範囲に相当するデータの個数を度数という。そして、あたいによって度数がどのようになっているかを示したものを度数分布という。

***** 8.2 棒グラフ・円グラフ・帯グラフ

棒グラフ :: 度数を長さで表現，大きさの比較

注意点 分類を多くしすぎると度数が小さく，見難くなる
縦軸の目盛りを適切にすること

円グラフ :: 度数の比率 帯グラフ :: 度数の比率と大きさも表せる

円グラフ帯グラフの注意点 ・調査対象数を記すこと ##### 8.3 ヒストグラム
ヒストグラムとは :: 柱状図。項目値が間隔・比尺度のとき，値の範囲 を
/階級/ と呼び，相当するデータの度数を表す。

*** 9章--代表値を求める

***** 9.1 代表値とは

代表値とは :: 度数分布の特徴をわかりやすく表す方法

項目に関して1つの数値で表現する

平均値，中央値，最頻値などがある。これらを/中心傾向/と呼ぶ。

***** 9.2 平均値を求める

平均値とは :: ある項目について，すべての項目値を足し合わせ，個数
で割った，平均値。ヒストグラムの重心を表現する。

式 :: bar(x) = !/(1..N) x/i /N

***** 9.3 中央値を求める

中央値とは :: データを大小順に並べたときの真ん中の値

***** 9.4 最頻値を求める

最頻値とは :: 最も度数分布の多い値。分布の山の一番高いところ。

*** 10章--散布度を求める

***** 散布度とは

平均が同じ分布であっても広がり具合が違えばデータの様子は大きく異なる。この分布の広がり具合の程度を表す指標を散布度という。
##### 標準偏差 (SD) とは 個々のデータが平均値からどのくらい離れてい
るかを集計し，平均した値。

標準偏差は，項目値と同じ単位で表される。
小さければ分布の中心から離れていない，分布が狭い範囲にあることを 示す。
大きければ，平均値から離れたところにもデータがたくさんあり，分布
が広い範囲にあることを示す。

*** 11章--正規分布と相対的な位置

***** 正規分布とは？

正規分布は完全に左右対称の分布であり、統計では最も頻繁に使われる分布である。データを大量に収集すると正規分布に近づく。
##### 標準正規分布 ものさしとなる正規分布 平均値が0 標準偏差（分散）が１

*** 12章--標準得点と偏差値

***** 標準得点とは

標準得点 :: 標準正規分布上で表される得点のこと
個人の得点が平均値からどの程度離れているかを，
標準偏差の倍数で表したもの ##### 標準得点の意味と活用
異なる平均値や標準偏差をもつ複数の分布の間で，得点の大小を比較し
ようとするときに便利な方法 ##### 偏差値
標準得点を，平均点50点，標準偏差10点と変換した値 ###
13章--クロス集計表と散布図 ##### クロス集計表とは
アンケートの設問項目について，2つの項目に注目して同時に集計するこ
とをクロス集計という。 ##### 散布図とは
散布図は一対の項目値を，ｘ軸とy軸上に表現したもの

*** 14章--いろいろな相関関係の表現

***** ピアソンの積率相関係数 (r) とは

ピアソンの積率相関係数 (r) とは ::
2つの項目がいずれも間隔・比尺度である場合に両者の間に直線関係があるかを示す指標

#+BEGIN_HTML
  <dl>
  <dt> 
#+END_HTML

r = (xとyの共分散) / (xの標準偏差）× (yの標準偏差)

#+BEGIN_HTML
  </dt>
  <dt>   
#+END_HTML

= !/{1..N} (Z/x × Z\_y) / N

#+BEGIN_HTML
  </dt>
  </dl>
#+END_HTML

r は −１<= r <= +1 となり，

1. 1 に近いと正の相関

-  1 に近いと負の相関 （逆） 0に近いと相関なし

